### ISSUE TITLE
Экранирование 

### ISSUE THREAD

**Issue by AndreiTsvirenko** [moshenskyDV/IP-Control#1]
Вот пример сообщения, при блокировки пользователя:
a tittle=\\\"qwe\\\">img src=\\\\\\\"http://memesmix.net/media/created/foel7t.jpg\\\\\\\" alt=\\\\\\\"q99\\\\\\\"</a
оно всё экранировано.
Экранирование происходит при сохранении настроек.
С каждым нажатием сохранения настроек экранирование увеличивается в арифметической прогрессии.

**Comment by moshenskyDV** [comment]
Fixed in v 1.0.1
(commit: 079677a115f4b54eeec7b7638918b38c4d8a2bac)
